### ISSUE TITLE
Parameter list needs improvisation

### ISSUE THREAD

**Issue by Shrutisd1003** [Atharva-Thakur/Insights#16]
<img width="511" alt="Screenshot 2024-04-20 144138" src="https://github.com/Atharva-Thakur/Insights/assets/113239067/5fc4070a-1c73-4594-8496-3c2f8025834c">

<img width="461" alt="image" src="https://github.com/Atharva-Thakur/Insights/assets/113239067/e75fad65-69a0-4085-b9c8-4eb248540320">

KNN regressor model (or any regressor model) does not take or predict categorical data, so what I am saying we do not display variables that the model is not compatible with in the first place instead of giving an error.

**Comment by Atharva-Thakur** [comment]
Solved in b58b9562a9860d033b694deb731d26615f533697
